### ISSUE TITLE
Wheel listener retains context

### ISSUE THREAD

**Issue by valerij-usachov** [ariutta/svg-pan-zoom#181] opened 2015-12-25 15:22 UTC
wheelListener causes detached DOM trees, it is not unbinded on destroy in fact.

![063](https://cloud.githubusercontent.com/assets/7606951/12003501/e829b954-ab2a-11e5-8d37-d78682e3d8ea.png)

```javascript
/**
 * Enable ability to zoom using mouse wheel
 */
SvgPanZoom.prototype.enableMouseWheelZoom = function() {
  if (!this.options.mouseWheelZoomEnabled) {
    var that = this

    // Mouse wheel listener
    this.wheelListener = function(evt) {
      return that.handleMouseWheel(evt);
    }

    // Bind wheelListener
    Wheel.on(this.options.eventsListenerElement || this.svg, this.wheelListener, false)

    this.options.mouseWheelZoomEnabled = true
  }
}

/**
 * Disable ability to zoom using mouse wheel
 */
SvgPanZoom.prototype.disableMouseWheelZoom = function() {
  if (this.options.mouseWheelZoomEnabled) {
    Wheel.off(this.options.eventsListenerElement || this.svg, this.wheelListener, false)
    this.options.mouseWheelZoomEnabled = false
  }
}
```
There is no need in: 
```javascript
 var that = this

    // Mouse wheel listener
    this.wheelListener = function(evt) {
      return that.handleMouseWheel(evt);
    }
```

```wheelListener``` eventually retains the context.

we can just pass ```this.handleMouseWheel``` instead of ```this.wheelListener``` in both places:

```javascript
Wheel.on(this.options.eventsListenerElement || this.svg, this.wheelListener, false)
Wheel.off(this.options.eventsListenerElement || this.svg, this.wheelListener, false)
```

and so no need in 
```javascript
var that = this

    // Mouse wheel listener
    this.wheelListener = function(evt) {
      return that.handleMouseWheel(evt);
    }
```

**Comment by bumbu** [comment] 2015-12-27 11:27
Passing `this.handleMouseWheel` instead of `this.wheelListener` will raise errors as `this.handleMouseWheel` will be called with event context (instead of svgPanZoom context). So this will not help.

`this.wheelListener` can be freed by deleting it (or setting its value as null).

I did test this behavior by myself and I can't reproduce that bug:
![image](https://cloud.githubusercontent.com/assets/171178/12010028/3b068172-ac8c-11e5-9bb0-79ca63dacd66.png)

Maybe you have some other code that actually retains the context? Or you didn't wait enough time for GC to do its job. Or you have an older version of library.

It would be great if you could provide an [reproductible](https://github.com/ariutta/svg-pan-zoom#bugs-and-issues) example.

**Comment by valerij-usachov** [comment] 2015-12-28 11:00
Thanks for quick feedback. For now, I can't provide an producible example. I'll try to figure out more detailed why it happens. 
About "you didn't wait enough time for GC to do its job" - from [docs](https://developer.chrome.com/devtools/docs/javascript-memory-profiling): "taking a snapshot always starts with doing a GC", so I think this is not a reason.
About "Or you have an older version of library" - I use `svg-pan-zoom v3.2.5`

For now, I can get rid of this problem (detached DOM tree) by disabling mousewheel zoom (by passing `mouseWheelZoomEnabled: false` in config).

**Comment by bumbu** [comment] 2015-12-28 12:01
Ok, I'll close it then for now. I'll reopen it if we'll have a reproducible example.

**Closed by bumbu** 2015-12-28 12:01 UTC
Labels: bug, discussion
