### ISSUE TITLE
Not able to do ZOOM/PAN while adding svg data to object dynamically

### ISSUE THREAD

**Issue by rajeshchinnam** [ariutta/svg-pan-zoom#85] opened 2015-02-03 11:27 UTC
Hi,
Thanks in advance.
I am trying to load data attribute to svg object dynamically on click of a button through javascript function call
below was my code
<!DOCTYPE html>
html
  head
    script src="svg-pan-zoom.js"
	 script
        // Don't use window.onLoad like this in production, because it can only listen to one function.
	  function enable(filepath){
		document.getElementById("demo-tiger").data=filepath;
		svgPanZoom('#demo-tiger', {
          zoomEnabled: true,
          controlIconsEnabled: true
        });
	  }

    script
  head
  body
object id="demo-tiger" type="image/svg+xml" style="width: 500px; height: 500px; border:1px solid black; "/object
button type='button' id="svg1" value="file1" onclick="enable('tiger.svg');return false;">file 1/button
  /body
/html
![loadsvg](https://cloud.githubusercontent.com/assets/4436035/6019430/62304d72-abc6-11e4-9417-4366cbe440ab.png)

by this way I am Not able to do ZOOM/PAN while adding svg data to object dynamically
I am getting below error

Uncaught TypeError: undefined is not a functionsvg-pan-zoom.js:488 
ShadowViewport.getCTMsvg-pan-zoom.js:400 
ShadowViewport.processCTMsvg-pan-zoom.js:330 
ShadowViewport.initsvg-pan-zoom.js:302 
ShadowViewportsvg-pan-zoom.js:622 
module.exportssvg-pan-zoom.js:677 
SvgPanZoom.initsvg-pan-zoom.js:633 
SvgPanZoomsvg-pan-zoom.js:1341 
svgPanZoomobject.html:10 enableobject.html:20 
onclick

When I debug in the JS, I found error at
var safeCTM = this.options.svg.createSVGMatrix() showing error message "Uncaught TypeError: undefined is not a function"
Could some one help me to resolve this issue

Thanks
Rajesh

**Comment by bumbu** [comment] 2015-02-03 12:39
This is a duplicate of #84
An explanation and solution is posted in that issue.

**Closed by bumbu** 2015-02-03 12:39 UTC
Labels: duplicate
