### ISSUE TITLE
strange zoom effect after dynamically load SVG element

### ISSUE THREAD

**Issue by korbai** [ariutta/svg-pan-zoom#257] opened 2017-07-21 09:23 UTC
Hi,

I tried to load SVG elements via ajax calls. In the first call everything was okay, but at the subsequent calls a strange zoom effect occured. I tried to destroy instance/element you mentioned in [issue #84](https://github.com/ariutta/svg-pan-zoom/issues/84) but the result is the same.

I tried the fit/contain parameter too, but these did not help. If I use fit: false, then the first call is ok again, but at the second call the objects disappear from the view.

I made an absolute minimal example to reproduce my problem: [jsfiddle](https://jsfiddle.net/korbai/93fxaahk/)

### Steps to reproduce the behaviour

1. initialize, ok, you can see 3 hexagon objects, size/zoom/pan not changed during initialize
2. destroy
3. initialize, not ok, you can see the big zoom effect

### Configuration

- svg-pan-zoom version: `3.5.1`
- Browser(s): `chrome 59.0.3071.115 64 bit`
- Operating system(s): `windows 10`
- A relevant example URL: [jsfiddle](https://jsfiddle.net/korbai/93fxaahk/)

Thanks,
Zoltan

**Comment by bumbu** [comment] 2017-07-23 21:09
Hi @korbai,

Thank you for the report. Actually this is a duplicate of #171 plus a bug in the code you provided. 

## About the bug:

Initially you're cloning your SVG `element = $('#map').clone();` - that's perfectly fine. 
But then right before initializing the library, you're using the cloned element:
```js
$('#map').replaceWith(element);
instance = svgPanZoom('#map', {})
```

`replaceWith` doesn't clone the element. You can see in [this example](https://jsfiddle.net/bumbu/93fxaahk/5/) that after you do: initialise, destroy, initialise - the SVG has the `viewBox` removed, while it should have it back as the intention was to restore the SVG. That means that you're always using the same SVG instance, and cloning wasn't of any use.

The solution is as simple as ([example](https://jsfiddle.net/bumbu/93fxaahk/6/)):
```js
$('#map').replaceWith(element.clone());
instance = svgPanZoom('#map', {})
```

I'm going to close this issue as a duplicate of #171, but feel free to comment on this or that issue if you have any further concerns.

**Closed by bumbu** 2017-07-23 21:09 UTC
