### ISSUE TITLE
External inputs do not blur when clicking on panzoomed Element

### ISSUE THREAD

**Issue by dzza** [ariutta/svg-pan-zoom#288] opened 2018-03-24 00:51 UTC
Bug report
---

### Expected behaviour
Inputs that are located outside of the panZoomed element and that are in state `focus` should [blur](https://developer.mozilla.org/en-US/docs/Web/Events/blur) (unselect/lose focus) when clicking on the panZoomed element.

### Actual behaviour
Inputs remain focused.

### Steps to reproduce the behaviour
1 Click on input
2 Click on panZoomed element

https://jsfiddle.net/r32zftk0/

**Comment by bumbu** [comment] 2018-03-24 11:06
Hey @dzza, 

Can you please explain what do you mean by **blur**? Also what do you mean by **external inputs**?
Maybe you have some screenshots to explain what's the bug exactly?

I opened the jsfiddle and everything seems to be working as expected.

**Comment by dzza** [comment] 2018-03-24 18:07
Hi bumbu, thanks for your quick response. Edited issue for clarity

**Comment by bumbu** [comment] 2018-03-24 18:38
That's not a bug. Try disabling the `preventMouseEventsDefault` option (see fiddle). This will not prevent mouse events and should achieve what you're trying to do. 

https://jsfiddle.net/r32zftk0/1/

If that's the case, please close the issue. If not then please give more details.

**Comment by dzza** [comment] 2018-03-24 19:27
Indeed. Is it possible to preventMouseEvents for all except click (or other way around)? 

The input blurs as expected, however mouseWheel gets detected by body and scrollng the panZoomed element scrolls the page as well.

Thanks again for quick response

**Comment by bumbu** [comment] 2018-03-24 23:11
Currently there is no option to disable prevent for just one specific event. Few possible solutions:

* Try registering event listeners for clicks on the SVG before initialising the plugin. Having that you can un-focus what you need manually
* Look into [custom events](https://github.com/ariutta/svg-pan-zoom#demos)
* For the repo and change the source code as you need it

Each method has it's own draw-back, but these are the only things I could think of.

**Comment by bumbu** [comment] 2018-08-28 19:49
Closing as no further comments provided

**Closed by bumbu** 2018-08-28 19:49 UTC
Labels: incomplete
