### ISSUE TITLE
Viewport Error in Firefox

### ISSUE THREAD

**Issue by isenegger-t** [ariutta/svg-pan-zoom#92] opened 2015-02-18 13:57 UTC
Included svgPanZoom in our Project like this:

$scope.map = svgPanZoom('#svg2', {
		  zoomEnabled: true,
		  controlIconsEnabled: true,
		  panEnabled:true,
		  fit: true,
		  center: true,
		  viewportSelector: document.getElementById('svg2').querySelector('#layer2')
		}

Also set some attributes:

                var group = document.createElement("g");
		group.setAttribute('inkscape:groupmode','layer');
		group.setAttribute('id','layer3');
		group.setAttribute('inkscape:label','x-Ebene');
		group.setAttribute('style','display:inline');
		group.setAttribute('transform','translate(311.9375,362.22079)');
		group.setAttribute('sodipodi:insensitive','true');
		
		var polygon = document.createElement("polygon");
		polygon.setAttribute('id', 'closecross');
		polygon.setAttribute('points', '51.5,51.1 79.6,23 77.6,21.1 49.6,49.2 21.5,21.1 19.6,23 47.6,51.1 19.6,79.2 21.5,81.1 49.6,53 77.6,81.1 79.6,79.2');
		polygon.setAttribute('style', 'fill:#010101');
		polygon.setAttribute('transform', 'transform="matrix(0.2906843,0,0,0.2754584,669.53441,-354.06261)');
		
		group.appendChild(polygon);
		document.getElementById('svg2').appendChild(group);

In Google Chrome, everything works fine - but in Firefox, this Error is displayed:

[Exception... "Failure"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: http://localhost/suche/script/svg-pan-zoom.js :: [4]</SvgPanZoom.prototype.cacheViewBox :: line 398"  data: no]
http://localhost/suche/script/svg-pan-zoom.js
Line 398

Any idea what this could be?

Thank you in Advance.
Best regards

**Comment by bumbu** [comment] 2015-02-19 14:47
Can you please post this code somewhere where I could test it (like jsfiddle)?
What version of svg-pan-zoom do you use?
Do you alter SVG after svg-pan-zoom initialization or before?

**Comment by bumbu** [comment] 2015-03-18 04:49
Closing this as I can't reproduce it. Feel free to reopen with a jsfiddle example.

**Closed by bumbu** 2015-03-18 04:49 UTC
Labels: bug, question

**Comment by arvinsim** [comment] 2015-03-26 06:41
I have the same problem somewhat with the other guy.

I am using version 3.1.1
I get an `NS_ERROR_FAILURE:` error on line 361 in the unminified version of the file. This only
happens in Firefox and not in Chrome.

    ...
        // Force updating CTM
        this.updateCTMOnNextFrame()

        this.options.svg.removeAttribute('viewBox')
    } else {
        var bBox = this.viewport.getBBox(); // <-- error is triggered here.

        // Cache viewbox sizes
        this.viewBox.x = bBox.x;
        this.viewBox.y = bBox.y;
        this.viewBox.width = bBox.width
        this.viewBox.height = bBox.height
    ...
