### ISSUE TITLE
thumbnailViewer not working locally

### ISSUE THREAD

**Issue by gwinnc** [ariutta/svg-pan-zoom#287] opened 2018-03-22 17:20 UTC
Hi there!

Thanks for submitting an issue to svg-pan-zoom.

To help us help you better, please do the following before submitting an issue:

1. Review:
  * Available documentation https://github.com/ariutta/svg-pan-zoom/blob/master/README.md
  * Common Issues & FAQ https://github.com/ariutta/svg-pan-zoom#common-issues--faq
  * Existing examples https://github.com/ariutta/svg-pan-zoom#demos
1. Check if the same bug/feature request [wasn't previously reported](https://github.com/ariutta/svg-pan-zoom/issues?q=is%3Aissue%20)
1. Make sure you are not asking a usage or debugging question. If you are, use [StackOverflow](http://stackoverflow.com/questions/tagged/svgpanzoom).
1. Fill in the information that corresponds to your type of issue below
1. If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: http://jsfiddle.net/bumbu/167usffr/).
1. Delete this intro and any unrelated text :smile: (if you do not we'll assume you haven't read these instructions and automatically close the issue)

Bug report
---

### Expected behaviour
Open file and be able to zoom and pan image

### Actual behaviour
Image and thumbnail image load. No functionality

### Steps to reproduce the behaviour

1. Open file on computer
2. Not able to zoom and no zoom (+) or (-) buttons or reset button on screen.

### Configuration

- svg-pan-zoom version: ``
- Browser(s): `IE 11, Chrome 65`
- Operating system(s): `Windows 7`
- A relevant example URL:

Feature Request
---

Am I missing something about how this is supposed to work? I looked in the read me and on StackOverflow and did not see any documentation on this issue.

**Comment by bumbu** [comment] 2018-03-24 11:04
Hi @gwinnc,

Do you run a server locally? Is http://jsfiddle.net/bumbu/167usffr/ working for you?
It seems to be a duplicate of #260 so I'm closing it. But feel free to comment if that's not the case and I'll reopen it.

**Closed by bumbu** 2018-03-24 11:04 UTC
