### ISSUE TITLE
Safari: Trouble with stretching SVG to 100% width/height of the container

### ISSUE THREAD

**Issue by cibulka** [ariutta/svg-pan-zoom#305] opened 2018-07-17 12:33 UTC
Bug report
---

Thanks for an awesome library! I'm using it to rendering a clickable seating plan, that should stretch across width and height of the container. My markup goes roughly as this:

```
<div style="display: grid; grid-template-columns: 1fr 3fr; height: 100vh;">
  <div>Sidebar</div>
  <div>
    <div id="panzoom" style="position: absolute; width: 100%; height: 100%;">
        <svg width="100%" height="100%" />
    </div>
  </div>
</div>
```

`svg-pan-zoom` calculates initial `transform` configuration for `g` wrapper (generated by `svg-pan-zoom`) correctly in all browsers I have access to (Chrome, Firefox, Opera): `transform: matrix(0.993291, 0, 0, 0.993291, -29.6994, -21.7873);`. Not in Safari though: `transform: matrix(0, 0, 0, 0, 266.2734375, 0);`. 

If I set fixed dimmensions to SVG (`width="400" height="400`), panzoom is able to guess the correct transform in Safari as well: `matrix(1.1258092140241718,0,0,1.1258092140241718,0.33774297893833705,86.5747184660987)`. 

I guess the quick workaround would be to calculate container dimmensions via javascript and hardcode them to wrapping SVG. I would really like not to do that though. :)

### Expected behaviour

Consistent behaviour across all browsers.

### Actual behaviour

`svg-pan-zoom` does not seem to guess the right `transform` configuration if dimmensions of the SVG are not set explicitly.

### Steps to reproduce the behaviour

My markup is bit more complicated than the example I posted above, but maybe this will give you an idea?

### Configuration

- svg-pan-zoom version: `3.5.3`
- Browser(s): `Safari 11.11.2`
- Operating system(s): `OSX 10.13.6 `
- A relevant example URL: ---

**Comment by bumbu** [comment] 2018-07-21 10:44
I tried reproducing this bug, but it seems to be working fine for me in Safari. 
See this fiddle http://fiddle.jshell.net/167usffr/2318/show/light/

Library relies on browser telling it the SVG size, so it's down to the user to make this work. The JS approach that you mentioned should work as an ultimate solution, but I feel that playing with CSS should solve the issue.

**Comment by bumbu** [comment] 2018-08-28 19:48
Closing as no further details provided

**Closed by bumbu** 2018-08-28 19:48 UTC
Labels: bug

**Comment by snaill** [comment] 2019-07-22 06:58
In Safari, svg element has default width/height
SvgPanZoom use clientWidth/clientHeight init itself
you set svg "width:100%, height: 100%" 
so error, and error, error...

try this:

            svg.setAttribute('width', parent.clientWidth + "px");
            svg.setAttribute('height', parent.clientHeight + "px");
            window.panZoom = SvgPanZoom(svg, {});
