### ISSUE TITLE
Mobile Issue Binding Click

### ISSUE THREAD

**Issue by ankushsaxena5** [ariutta/svg-pan-zoom#177] opened 2015-12-16 06:05 UTC
I am binding clicks to an svg which is using svg-pan-zoom like below. Everything works fine on desktop, aka clicking on an element with the class name "goToBuilding" scrolls down the page. 

However on mobile (iphone and Android) clicking on the element doesn't do anything. Do you know what might cause this? The reason I suspect it might be the package is because when I comment out the svgPanZoom, clicking on the svg elements works and scrolls down as expected on mobile.

Here's a live working example: http://paulhwang.meteor.com/ 
Clicking on the colored boxes on the SVG scrolls you down the page. But on mobile, it fails to work

````
    initMap = function()
    {
        gpz = svgPanZoom('#mapsvg', {
          viewportSelector: '.svg-pan-zoom_viewport'
        , panEnabled: true
        , controlIconsEnabled: true
        , zoomEnabled: true
        , dblClickZoomEnabled: true
        , mouseWheelZoomEnabled: false
        , preventMouseEventsDefault: true
        , zoomScaleSensitivity: 0.2
        , minZoom: 1
        , maxZoom: 2
        , fit: true
        , contain: true
        , center: true
        , refreshRate: 'auto'
        , beforeZoom: function(){}
        , onZoom: function(){}
        , beforePan: function(){}
        , onPan: function(){}
        , eventsListenerElement: null
        });

        $(window).resize(function() {
            clearTimeout($.data(this, 'resizeTimer'));
            $.data(this, 'resizeTimer', setTimeout(function() {
                gpz.resize()
                gpz.center()
                gpz.resetZoom()
                gpz.fit()
                // alert("Haven't resized in 200ms!");  
                console.log("resize");
            }, 1000));
        });

        bindMapClicks();
    }
    bindMapClicks = function()
    {
        var p = document.getElementById("mapsvg").getSVGDocument().getElementsByClassName("goToBuilding");

        $(p).click(function(){ 
            console.log($(this));
            var building = $(this).attr("building-num");
            console.log(building);

            if (building == -1)
            {
                window.open("http://skyboxrealty.com/");
                return;
            }

            var offset = $("[building="+building+"]").offset();
            console.log(offset,building);
            $('html, body').animate({
                scrollTop: offset.top
            }, 1000, 'easeInOutQuad');
            // $("[building=1]").offset()
        });
    }
````

**Comment by bumbu** [comment] 2015-12-16 22:32
I was able to reproduce the bug on your website with Desktop Google Chrome with touch events.

It should work fine on mobile phones. I did try to attach an event listener to the `goToBuilding` element. I did attach `click` and `touchstart` events. They both did pass. Which means that the problem should be in your script (maybe `$(p).click` listens only for click events, and not for touch events. 

Also it is hard to test that on your website as everything is compressed and it is not clear which versions of library you use. 

I'm closing that as it seems to be an issue with your code. If you still think it is the library issue then please provide an [easy to test use-case](https://github.com/ariutta/svg-pan-zoom#bugs-and-issues) and I'll reopen this issue.

**Closed by bumbu** 2015-12-16 22:32 UTC

**Comment by ankushsaxena5** [comment] 2015-12-17 00:05
Thanks, adding touchstart fixed the issue.
