### ISSUE TITLE
SVG automatic Pan onchange event

### ISSUE THREAD

**Issue by gitalvininfo** [ariutta/svg-pan-zoom#301] opened 2018-06-06 06:28 UTC
So I'm currently using panzoom andI'm stuck in this problem for almost two weeks now. So I have a massive SVG map. I provided a zooming and panning to the map using svg pan zoom. What I want to achieve is when I select an option in the drop down list, it will automatically pan to the selected area when the map is zoomed. I've tried every solution of panzoom that I think is related to my problem but it won't work. Thanks in advance. Please anyone help.

**Comment by bumbu** [comment] 2018-06-09 11:36
Hi @gitalvininfo, the library doesn't provide this functionality out of the box.
But this question looks like a duplicate of #212 which provides some code example for a potential solution. I'm going to close it in favour of that issue. Please feel free to comment/reopen if it's not the case.

**Closed by bumbu** 2018-06-09 11:36 UTC

**Comment by gitalvininfo** [comment] 2018-06-11 02:41
Thanks bumbu. I appreciate your help.
