### ISSUE TITLE
The inline SVG with this plugin doesn't work for responsive fullscreen CSS or HTML

### ISSUE THREAD

**Issue by gusbemacbe** [ariutta/svg-pan-zoom#268] opened 2017-11-04 07:23 UTC
Bug report
---

### Expected behaviour
The inline SVG will no longer work with the responsive fullscreen if you use this plugin.

### Actual behaviour
This plugin doesn't let it fit the responsive fullscreen to any resized window. 

### Steps to reproduce the behaviour

1. You add `height: auto; width: 100%` which allows the SVG to resize itself when you resize the window or on any mobile and tablet.

```html
<div style="width: 100%; height: auto">
 	<?xml version="1.0" encoding="UTF-8"?>
 	<svg id="test-svg" width="100%" height="auto" viewBox="0 0 2150 2800" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
         ...
       </svg>
</div>
```

2. I set like:

```javascript
<script>
  window.onload = function() {
    window.zoomTiger = svgPanZoom('#test-svgr', {
      zoomEnabled: true,
      controlIconsEnabled: true,
      fit: true,
      contain: true,
      center: true,
    });
    document.getElementById('enable').addEventListener('click', function() {
      window.zoomTiger.enableControlIcons();
    })
    document.getElementById('disable').addEventListener('click', function() {
      window.zoomTiger.disableControlIcons();
    })
  };
</script>
```

Here are the screenshots:

In this screenshot, it doesn't fulfil the height. It fulfils only the width.

![Screenshot 1](https://user-images.githubusercontent.com/2257024/32403239-fc854036-c11b-11e7-9774-746f7e3e030e.png)

And when you resizes the window, the SVG doesn't resize itself the width. 

![Screenshot 2](https://user-images.githubusercontent.com/2257024/32403243-16e3cbe6-c11c-11e7-8761-4bc6c50637a9.png)

Observe that I have already added `<meta name="viewport" content="width=device-width, initial-scale=1">` and it is still the same bug.

### Configuration

- svg-pan-zoom version: `` 3.5.2``
- Browser(s): `` Safari 11.0.1``
- Operating system(s): ``macOS High Sierra 10.13.1``
- A relevant URL: http://jsfiddle.net/gusbemacbe/27tmmdjz/5/

**Comment by bumbu** [comment] 2017-11-04 23:43
Hi @gusbemacbe 

You have to provide a desired height (e.g. pixels or percentage) otherwise as the library removes the viewBox property from the SVG - it will get some default height. 
For [example, by setting SVGs height to `90vh`](http://jsfiddle.net/bumbu/27tmmdjz/6/) it now expands vertically to 90% of the screen.

![image](https://user-images.githubusercontent.com/171178/32410521-fcf6c69a-c1b9-11e7-8da6-0b2237025c0b.png)

**Comment by gusbemacbe** [comment] 2017-11-05 00:41
@bumbu, the problem is that, due to `90vh`, on mobile or on small windows, there is much dark greyish blue space in top and bottom sides, for example:

![Screenshot 3](https://user-images.githubusercontent.com/2257024/32410815-e32ec8ba-c1b0-11e7-9872-beea2b5bc897.png)

Does this plugin offer to move the SVG to the left instead of center?

![Screenshot 4](https://user-images.githubusercontent.com/2257024/32410818-0bd90df2-c1b1-11e7-9e73-1943abdff868.png)

In this screenshot, there is much dark greyish blue space in the left side.

**Comment by bumbu** [comment] 2017-11-05 22:55
Hi @gusbemacbe 

This doesn't look like a bug. 
It's more about that specific SVG and what settings you pass to the plugin. 
I'm not sure what's the exact effect you try to achieve, but you'll have more luck on [asking this question on StackOverflow](https://github.com/ariutta/svg-pan-zoom/#questions-how-tos-need-help). 

I'll close this issue as it's not a bug, but if you still think that's a bug then feel free to reopen/comment on it.

**Closed** 2017-11-05 22:56 UTC
Labels: invalid, question
