### ISSUE TITLE
WP admin

### ISSUE THREAD

**Issue by gegato** [ariutta/svg-pan-zoom#100] opened 2015-03-06 09:26 UTC
in frontend page it works correctly but in admin 
 Error: Invalid value for <g> attribute transform="matrix(NaN,0,0,NaN,NaN,NaN)"
 Error: Invalid value for <g> attribute transform="matrix(1,0,0,1,NaN,NaN)"

svg-pan-zoom.min.js:1 line 1

**Comment by bumbu** [comment] 2015-03-07 06:43
Can you please provide more details? A link to working/not working example would be helpful.

**Comment by bumbu** [comment] 2015-03-10 05:40
Closing for now. If you have more details (or an example) you can reopen it.

**Comment by lucasbeef** [comment] 2015-03-20 15:25
I think I know why, I had the same problem.
Try it with the option 'fit' set to false. What happens is that it calculates the position of the image before the viewport is inserted.

Line 256 : If the initialisation of svgPanZoom comes too early my viewport width and height will be of 0, so we get a division by 0 wich results in a newScale = infinity which fucks with the matrice.

**Comment by bumbu** [comment] 2015-03-20 17:00
I did try disabling fit and it woks fine for me. Also I'm sure that if the issue would be solely in this parameter then more people would write about it.

Can you give me an example (jsfiddle would be perfect). Or at least:
- Browser name and version
- Library version
- SVG file
- Code that does initialization of svg-pan-zoom

This way I'll be able to help you.

**Comment by lucasbeef** [comment] 2015-03-21 13:48
It's not a problem about the fit option in itself. Actually, the problem doesn't come from the lib at all but from the fact that the code for fitting the svg is executed before the svg is inserted in the page.

Well I assume it's @gegato 's problem here, since I made the same mistake resulting in a similar error (see my previous comment).

So just desactivating the fit option fixed it for me, but an other solution (and the best option) would be to make sure the svg is properly inserted before triying to manipulate it with the lib (and I'm saying that to @gegato , again the problem doesn't come from the library), this way the fitting will work.

**Comment by bumbu** [comment] 2015-03-21 17:47
Oh, so you're talking about SVG's that are not loaded in page (embeded SVGs?).
There is an example for waiting SVG to load in [demo/dynamic-load.html](https://github.com/ariutta/svg-pan-zoom/blob/master/demo/dynamic-load.html).

**Closed by bumbu** 2015-03-21 17:47 UTC
Labels: bug

**Comment by lucasbeef** [comment] 2015-03-23 10:14
Yeah, thats right.
Thanks, I didnt see that !

Cheers ;)

**Comment by satabol** [comment] 2019-03-26 16:16
I got this on inline SVG. Is this right solution:
```Javascript
ShadowViewport.prototype.getCTM = function() {
  var safeCTM = this.options.svg.createSVGMatrix()

  // Copy values manually as in FF they are not itterable
  if ( isNaN(this.activeState.zoom) === false ) {
    safeCTM.a = this.activeState.zoom
  }
  safeCTM.b = 0
  safeCTM.c = 0
  if ( isNaN(this.activeState.zoom) === false ) {
    safeCTM.d = this.activeState.zoom
  }
  if ( isNaN(this.activeState.x) === false ) {
    safeCTM.e = this.activeState.x
  }
  if ( isNaN(this.activeState.y) === false ) {
    safeCTM.f = this.activeState.y
  }

  return safeCTM
}
```
???

**Comment by bumbu** [comment] 2019-03-30 03:56
Hi @satabol, can you please provide more context? 
A reproducible example with details (browser, version) would be helpful to understand your issue.

**Comment by voidz3ro** [comment] 2020-10-19 19:10
I'm getting this too, using inline svg. It doesn't always happen, only on occasion, still trying to determine why exactly. It does seem that some kind of prior check within setCTM is needed (just default to 0's if `typeOf(value)` isn't a float? 

![image](https://user-images.githubusercontent.com/8548855/96500674-dc52ec80-1214-11eb-9d83-0f821dffa2c4.png)

**Comment by voidz3ro** [comment] 2020-10-19 21:24
Fix was to delay rendering the component until our data was completely prepared. The data was manipulated inside a react useEffect() causing `svgPanZoom(elementId)` to be called three times quickly as the component rendered. I just added a conditional render to validate the final data was prepared.
